### ISSUE TITLE
The dialog "Configuring the project" takes forever

### ISSUE THREAD

**Issue by Petross404** [puzzlepaint/cide#4]
Basically the title. I opened a (qt) project with CIDE and the whole IDE is stuck and waiting the Configuring the project dialog to finish.

Any clue what is going on? Is it due to parsing? Maybe my system is at fault here?

**Comment by puzzlepaint** [comment]
I think that the time that this dialog takes should usually mostly depend on the time that CMake takes to configure the project. Possibly this project takes a while to configure with CMake?

I did not observe this yet for any of my projects, but I think this could easily happen in the case above. Ideally, CIDE should do this step in the background instead of in the foreground.

**Comment by Petross404** [comment]
> I think that the time that this dialog takes should usually mostly depend on the time that CMake takes to configure the project. Possibly this project takes a while to configure with CMake?
> 
Yes maybe you are right. What if cmake messages were visible? So we can see the progress of the process and if it failed?

**Comment by puzzlepaint** [comment]
That also seems like it would be a step in the right direction. I'll put it on my to-do list such that I'll consider it the next time I work on CIDE.

**Comment by Petross404** [comment]
IMO this issue can stay as open until further progress on the matter. If you feel it can be reopened feel free to close it.

**Comment by puzzlepaint** [comment]
Commit ac364e87a3bc9a9df0c37f7de741b0b21f816560 makes the progress dialog show the CMake output while configuring a project.

**Comment by Petross404** [comment]
It's nice and fast. Thank you for your work. Do you think this can now be closed?

**Comment by puzzlepaint** [comment]
I considered keeping this issue open, since it would still be preferable to do the whole configuration in the background while the editor widgets can be used. But that does not seem important for now and may be added as a separate issue, so let's close it.
